### ISSUE TITLE
travis errors since using versioneer

### ISSUE THREAD

**Issue by michaelaye** [warner/python-versioneer#114]
I attach the screenshot of Travis' error.
Could it have something to do that I need to add a test class to the cmdclass dictionary?
I am currently doing it like this:
```python
setup(
    name="planet4",
    version=versioneer.get_version(),
    # this hack just to combine 2 dictionaries, as versioneer automates the
    # cmdclass dic generation.
    cmdclass=versioneer.get_cmdclass().update({'test': PyTest}),
```

<img width="763" alt="screenshot 2016-04-21 18 11 28" src="https://cloud.githubusercontent.com/assets/69774/14727866/931e6f58-07ec-11e6-8c45-18e5cd38eba4.png">

**Comment by michaelaye** [comment]
Sorry, PEBKAC case.

**Comment by warner** [comment]
Glad it worked out for you :-)

BTW, one thing to be aware of with travis and large projects is that they do a shallow clone, and if there have been a lot of commits since the last tag, there won't be enough information for git (or Versioneer) to compute a full version.

I'm thinking of writing a script that repeatedly fetches more and more commits (deepens the shallow clone, maybe 100 commits at a time, doubling each time) until a tag is found, or the whole history has been retrieved. Projects that have this happen often can add a copy to their source trees, and then configure travis to run it as a build step before any builds or tests happen.

**Comment by pelson** [comment]
All the more reason to release frequently :wink:
