### ISSUE TITLE
cmdclass clash

### ISSUE THREAD

**Issue by has2k1** [warner/python-versioneer#128]
Versioneer creates a `cmdclass` and requires that the `setup` method uses that. While this works for the majority of packages, it breaks when a package must use a different `cmdclass`. For example numpy defines a [cmdclass](https://github.com/numpy/numpy/blob/6bb5a22ac873a76f4e80988469fe84c1067a7d58/numpy/distutils/core.py#L32). This `cmdclass` is also used by scipy and definitely relied upon by a bunch of other [scikits](http://scikits.appspot.com/scikits) -- those that follow the format specified by the [scikit-example](https://github.com/pv/scikit-example).

Specifically, the issue arises from 2 classes that Versioneer extends to create the `cmdclass` i.e `build_py` and `sdist`.

A solution would be to let `get_cmdclass()` take arguments for these base classes. i.e. having the a  signature like the following:

```python
get_cmdclass(build_py=None, sdist=None)
```
Such a change should be backwards compatible.

**Comment by warner** [comment]
Hm, so the Versioneer code would need to upcall to the numpy's version of e.g. `build_py`, instead of going directly to setuptools or distutils? And numpy is probably (internally) upcalling to setuptools's version?

Yeah, passing in arguments sounds like a decent approach to me. What if we just passed in a single "old cmdclass" dict, and if any of the overridden commands were defined in there, then Versioneer would upcall to them instead of setuptools/distutils? 

I'd like to put a sample here, but I'm having trouble finding a scikit example that pulls a cmdclass from numpy. I'm guessing it would look something like this:

```python
from setuptools import setup
import versioneer
from numpy import something
numpy_cmdclass = something.get_cmdclass()
cmdclass = versioneer.get_cmdclass(numpy_cmdclass)
setup(..., cmdclass=cmdclass)
```

**Comment by has2k1** [comment]
Using an "old cmdclass" is a better approach.

For `numpy` `cmdclass` examples, it is not straight forward to discern when browsing the `setup.py` files. The line to look out for is:

```python
from numpy.distutils.core import setup
```
You can see it in the [scikit-example](https://github.com/pv/scikit-example/blob/669cfd33a7252f04c361aaf31d1a59503339c40e/setup.py#L32) or even [scipy](https://github.com/scipy/scipy/blob/fa13ccb67808c263301f44041d411b6decf8b6e2/setup.py#L396).

The `setup` function from `numpy` [updates](https://github.com/numpy/numpy/blob/02e2ea815a6c76152096364edd10e2dd954bcb56/numpy/distutils/core.py#L111-L114) the `numpy cmdclass`.

I will submit a PR.
