### ISSUE TITLE
New release (0.14)?

### ISSUE THREAD

**Issue by jakirkham** [warner/python-versioneer#70]
Even though there was a release 0.13 not so long ago (and some dev releases since), it seems like a lot of really cool and useful features were added right afterwards (most notably the PEP440 improvements). IMHO these seem worthy of a version up tick. Thoughts?

**Comment by generalov** [comment]
+1 
We are forced to use `pip<1.6` because of compatibility issues with PEP440 of versioneer'ed projects.

**Comment by richardotis** [comment]
PEP 440 compatibility is definitely a big deal. As a workaround, you can pip install the latest master: `pip install git+https://github.com/warner/python-versioneer.git`

That will install it as version "0.13-dev". From there follow the "Updating Versioneer" instructions as if it's a normal upgrade. I don't normally recommend doing this but I think Versioneer is a special-case dependency since it gets embedded directly in your project, and you can just upgrade it from PyPI when 0.14 gets pushed.

**Comment by warner** [comment]
Cool, I'll make an 0.14 now. I've been pushing on the "style" branch (a new approach to the "template" branch, to let you pick which version style you want), but I got stuck on it. So yeah, a 0.14 with just the main PEP440 "TAG+DISTANCE" -style version strings is a good idea.

(Note that the corner cases may change between this 0.14 and whatever comes out next, as I figure out the "style" branch implementation: things like what version string to show when there are no tags at all).

**Comment by jakirkham** [comment]
@warner That sounds interesting. I don't mean to force your hand. If you feel it's not ready yet, that's fine. Just thought, you had some cool things that merited a release. :)

@richardotis Thanks for sharing. That's what I have done.

**Comment by warner** [comment]
Done, 0.14 is on pypi. Lemme know if you run into any problems.

**Comment by jakirkham** [comment]
Thanks.

**Comment by jakirkham** [comment]
Looks good so far. :)
