### ISSUE TITLE
python setup.py build fails

### ISSUE THREAD

**Issue by fwang2** [warner/python-versioneer#76]
Using the latest head version of versioneer, I am running into the following error when doing "python setup.py build"

    running build
    running build_py 
    UPDATING build/lib/_version.py
    error: [Errno 2] No such file or directory: 'build/lib/_version.py'

The `build/lib` actually have the `_version.py` present - is there anything I missed? 

Thanks

**Comment by fwang2** [comment]
never mind, I misconfigured `versionfile_build`, my bad.

**Comment by Xylambda** [comment]
The response pointed me to the right direction but I think it the answer can be better since there are multiple `versionfile_build` in the files added by versioneer. You have to go to `setup.cfg` and fix `versionfile_build`. 

In my case, I am using a project structure `pkt/src/pkt` and so my `setup.cfg` should be:

```python
[versioneer]
VCS = git
style = pep440
versionfile_source = src/pkt/_version.py
versionfile_build = pkt/_version.py
tag_prefix = v
```
